export const Constants = {
    graphql_public: {
        Enums: {},
    },
    public: {
        Enums: {
            automation_action_type: [
                "send_message",
                "schedule_message",
                "update_patient",
                "log_event",
                "webhook",
                "conditional",
                "delay",
            ],
            automation_trigger_type: ["appointment", "patient", "payment", "system"],
            body_region: [
                "cervical",
                "thoracic",
                "lumbar",
                "sacral",
                "shoulder",
                "elbow",
                "wrist",
                "hip",
                "knee",
                "ankle",
                "head",
                "other",
            ],
            body_side: ["front", "back"],
            calendar_integration_status: [
                "pending",
                "sent",
                "delivered",
                "failed",
                "cancelled",
            ],
            calendar_provider: ["google", "outlook", "apple", "ics"],
            communication_channel: ["email", "sms", "whatsapp", "push"],
            message_status: [
                "draft",
                "queued",
                "processing",
                "sent",
                "delivered",
                "read",
                "failed",
                "cancelled",
                "retry_scheduled",
            ],
            message_type: [
                "appointment_confirmation",
                "appointment_reminder",
                "appointment_cancellation",
                "payment_reminder",
                "welcome",
                "birthday_wishes",
                "treatment_completion",
                "no_show_followup",
                "generic",
            ],
            pain_type: ["acute", "chronic", "intermittent", "constant"],
            reminder_method: ["email", "popup", "sms"],
            template_category: [
                "appointment",
                "payment",
                "marketing",
                "system",
                "general",
            ],
        },
    },
};
